using RevitCheck.Core.Csv;
using RevitCheck.Core.Ir;
using RevitCheck.Core.Mapping;
using RevitCheck.MappingBuilder;
using Xunit;

namespace RevitCheck.MappingBuilder.Tests;

public class MappingAutoBuilderTests
{
    private static RevitModel Model(params ElementMetadata[] elements) => new() { Elements = elements.ToList() };

    private static ElementMetadata Element(long id, string? category, string? familyName, Dictionary<string, ParameterValue> parameters) => new()
    {
        ElementId = id,
        Category = category,
        FamilyName = familyName,
        Parameters = parameters,
    };

    private static ParameterValue Str(string value) => new() { StorageType = ParameterStorageType.String, RawString = value, DisplayString = value };
    private static ParameterValue Num(double value) => new() { StorageType = ParameterStorageType.Double, NumericValue = value, IsLength = true, DisplayString = value.ToString() };

    private static CsvTable Csv(string[] headers, params Dictionary<string, string>[] rows) => new()
    {
        Headers = headers,
        Rows = rows.Cast<IReadOnlyDictionary<string, string>>().ToList(),
    };

    [Fact]
    public void ExactNameMatch_PopulatesDefaultParameter()
    {
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue>
        {
            ["Asset_ID"] = Str("A1"),
            ["Owner"] = Str("Roads Authority"),
        }));
        var csv = Csv(new[] { "Asset_ID", "Owner" }, new Dictionary<string, string> { ["Asset_ID"] = "A1", ["Owner"] = "Roads Authority" });

        var result = MappingAutoBuilder.Build(model, csv, "Asset_ID");

        Assert.Equal("Owner", result.Mapping.Fields["owner"].DefaultParameter);
        Assert.Equal(ComparisonType.ExactString, result.Mapping.Fields["owner"].Comparison);
    }

    [Fact]
    public void UnmatchedColumn_NeverSilentlyGuessedIntoFields_SurfacesInDiagnosticsInstead()
    {
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue>
        {
            ["Asset_ID"] = Str("A1"),
            ["Depth"] = Num(450),
        }));
        var csv = Csv(new[] { "Asset_ID", "Girder Depth (mm)" },
            new Dictionary<string, string> { ["Asset_ID"] = "A1", ["Girder Depth (mm)"] = "450" });

        var result = MappingAutoBuilder.Build(model, csv, "Asset_ID");

        Assert.DoesNotContain("girder_depth_mm", result.Mapping.Fields.Keys);
        Assert.Contains(result.Diagnostics, d => d.Contains("Girder Depth (mm)") && d.Contains("no exact parameter-name match"));
        Assert.Contains(result.Diagnostics, d => d.Contains("Depth")); // the per-family parameter-name shortlist
    }

    [Fact]
    public void NumericSampleValues_InferNumericComparison_WithNoToleranceSetYet()
    {
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue>
        {
            ["Asset_ID"] = Str("A1"),
            ["Depth"] = Num(450),
        }));
        var csv = Csv(new[] { "Asset_ID", "Depth" }, new Dictionary<string, string> { ["Asset_ID"] = "A1", ["Depth"] = "450" });

        var result = MappingAutoBuilder.Build(model, csv, "Asset_ID");

        Assert.Equal(ComparisonType.Numeric, result.Mapping.Fields["depth"].Comparison);
        Assert.Null(result.Mapping.Fields["depth"].ToleranceMm);
    }

    [Fact]
    public void StringSampleValues_InferExactStringComparison()
    {
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue>
        {
            ["Asset_ID"] = Str("A1"),
            ["Owner"] = Str("Roads Authority"),
        }));
        var csv = Csv(new[] { "Asset_ID", "Owner" }, new Dictionary<string, string> { ["Asset_ID"] = "A1", ["Owner"] = "Roads Authority" });

        var result = MappingAutoBuilder.Build(model, csv, "Asset_ID");

        Assert.Equal(ComparisonType.ExactString, result.Mapping.Fields["owner"].Comparison);
    }

    [Fact]
    public void AutoGeneratedNumericField_CannotBeLoaded_UntilAHumanSetsTolerance()
    {
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue>
        {
            ["Asset_ID"] = Str("A1"),
            ["Depth"] = Num(450),
        }));
        var csv = Csv(new[] { "Asset_ID", "Depth" }, new Dictionary<string, string> { ["Asset_ID"] = "A1", ["Depth"] = "450" });
        var result = MappingAutoBuilder.Build(model, csv, "Asset_ID");

        var json = ParameterMappingSerializer.Dumps(result.Mapping);

        Assert.Throws<InvalidOperationException>(() => ParameterMappingSerializer.Loads(json));
    }

    [Fact]
    public void KeyColumn_IsNeverEmittedAsAField()
    {
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue> { ["Asset_ID"] = Str("A1") }));
        var csv = Csv(new[] { "Asset_ID" }, new Dictionary<string, string> { ["Asset_ID"] = "A1" });

        var result = MappingAutoBuilder.Build(model, csv, "Asset_ID");

        Assert.Empty(result.Mapping.Fields);
    }

    [Fact]
    public void DifferingKeyCsvColumn_IsAlsoNeverEmittedAsAField()
    {
        // Regression test: a real run against real data (2026-08-23) skipped
        // this exact case - the CLI had no way to pass a key_csv_column
        // distinct from the key parameter name, so a CSV whose key header
        // reads differently from the Revit parameter (e.g. "Asset
        // Identifier (Label)" vs ATM_Asset_Identifier) got its key column
        // auto-matched as a regular field instead of skipped.
        var model = Model(Element(1, "Structural Framing", "PC_I_Beam", new Dictionary<string, ParameterValue>
        {
            ["ATM_Asset_Identifier"] = Str("Abutment"),
            ["Owner"] = Str("Roads Authority"),
        }));
        var csv = Csv(new[] { "Asset Identifier (Label)", "Owner" },
            new Dictionary<string, string> { ["Asset Identifier (Label)"] = "Abutment", ["Owner"] = "Roads Authority" });

        var result = MappingAutoBuilder.Build(model, csv, "ATM_Asset_Identifier", keyCsvColumn: "Asset Identifier (Label)");

        Assert.DoesNotContain("asset_identifier_label", result.Mapping.Fields.Keys);
        Assert.Single(result.Mapping.Fields);
        Assert.Equal("Owner", result.Mapping.Fields["owner"].DefaultParameter);
    }
}
